# Generated by Django 4.2.11 on 2025-08-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_encrypted_pin_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
