# Generated by Django 4.2.4 on 2026-03-27 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='patient_id',
            field=models.CharField(blank=True, help_text='Patient ID e.g. HUPA0001P', max_length=12, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='GlucoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('glucose', models.FloatField(help_text='Blood glucose in mg/dL')),
                ('heart_rate', models.FloatField(help_text='Heart rate in bpm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
